[package]
name = "twofloat"
version = "0.1.0"
authors = ["Andrew Tribick <ajtribick@googlemail.com>"]

keywords = ["float", "precision", "numerics", "floating-point", "arithmetic"]
categories = ["algorithms", "mathematics", "science"]

readme = "README.md"
license = "BSD-3-Clause"
description = "A library providing double-double arithmetic."
repository = "https://github.com/ajtribick/twofloat"

edition = "2018"

[dev-dependencies]
rand = "0.7"
