[package]
name = "twofloat"
version = "0.1.0"
authors = ["Andrew Tribick <ajtribick@googlemail.com>"]

keywords = ["float", "precision", "numerics", "floating-point", "arithmetic"]
categories = ["algorithms", "mathematics", "science"]
exclude = ["/.travis.yml", ".gitignore"]
edition = "2018"

readme = "README.md"
license = "BSD-3-Clause"
description = "Double-double arithmetic functionality."
repository = "https://github.com/ajtribick/twofloat"

[dev-dependencies]
rand = "0.7"

[badges]
travis-ci = { repository = "ajtribick/twofloat", branch = "master" }
