[package]
name = "twofloat"
version = "0.4.1"
authors = ["Andrew Tribick"]

keywords = ["float", "precision", "numerics", "floating-point", "arithmetic"]
categories = ["algorithms", "mathematics", "science"]
exclude = [".gitignore", "sollya", ".github"]
edition = "2018"

readme = "README.md"
license = "BSD-3-Clause"
description = "Double-double arithmetic functionality."
repository = "https://github.com/ajtribick/twofloat"

[features]
default = ["math_funcs"]
math_funcs = []

[dependencies]
num-traits = "0.2.14"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
rand = "0.8"
serde_test = "1.0"
