[package]
name = "twofloat"
version = "0.4.1"
authors = ["Andrew Tribick"]

keywords = ["float", "precision", "numerics", "floating-point", "arithmetic"]
categories = ["algorithms", "mathematics", "science"]
exclude = ["/.travis.yml", ".gitignore", "sollya"]
edition = "2018"

readme = "README.md"
license = "BSD-3-Clause"
description = "Double-double arithmetic functionality."
repository = "https://github.com/ajtribick/twofloat"

[features]
default = ["math_funcs"]
math_funcs = []
serde_support = ["serde"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
rand = "0.7.3"
serde_test = "1.0"
